### PR TITLE
Expand root fs on raw

### PR DESCRIPTION
**Pull request by nothingneko**

### CODE REVIEW

**Comment by nothingneko** [comment]
i dont think we need repart and i think we can just do a oneshot systemd service that invokes growpart and resize2fs

```
[Unit]
Description= Expand rootfs
After=multi-user.target

[Service]
Type=oneshot
ExecStart=/usr/bin/growpart /dev/xx 3
ExecStart=/sbin/resize2fs /dev/xx3
RemainAfterExit=true

[Install]
WantedBy=multi-user.target
```
i don't think i need repart

**Comment by nothingneko** [comment]
Switched to a script that does it

**Comment by nothingneko** [comment]
Don't merge just yet, just need review now

**Comment by korewaChino** [comment]
why is this a package just make it a heredoc cat in the katsu scripts

**Comment by nothingneko** [comment]
Repart should work now, winning

**Review by lleyton — APPROVED** [review]

**Pull request merged**
