### PR TITLE
fix(flagship-filesystem): dependencies

### PR DESCRIPTION
**Pull request by sadlerm4**
terrapkg/packages#2246

### CODE REVIEW

**Comment by sadlerm4** [comment]
ahhh recommends not suggests...

**Comment by sadlerm4** [comment]
Will bump release here too

**Review by nothingneko — COMMENTED** [review]
why change from req?

**Comment by madonuko** [comment]
https://github.com/terrapkg/packages/issues/2246

**Comment by sadlerm4** [comment]
> why change from req?

You can't remove any of the applets because of req

All of the applets are req of budgie-extras, budgie-extras is req of filesystem, and filesystem is req of release-identity

**Review by nothingneko — APPROVED** [review]
do it

**Pull request merged**
