### PR TITLE
add mugshot to xfce

### PR DESCRIPTION
**Pull request by nothingneko**

### CODE REVIEW

**Comment by lleyton** [comment]
you might want to add a recommends to the xfce release subpkg and bump the release

**Comment by nothingneko** [comment]
sure, will do tomorrow

**Review by madonuko — COMMENTED** [review]
Bump version please?

**Comment by nothingneko** [comment]
thought i did oops

**Review by madonuko — APPROVED** [review]
btw why is this package not noarch

**Comment by nothingneko** [comment]
no idea

**Comment by lleyton** [comment]
wdym, it's `BuildArch: noarch`

**Comment by madonuko** [comment]
> wdym, it's `BuildArch: noarch`

I mean in anda.hcl

**Pull request merged**
