### PR TITLE
fix(comps): make release-identity-* optional in product groups

### PR DESCRIPTION
**Pull request by madonuko**
Done to make Ultramarine Hop (or just manually adding desktop environments) much easier

### CODE REVIEW

**Review by nothingneko — COMMENTED** [review]
we may want to consider making a Ultramarine Desktop identity for installs without a normal edition identity

**Comment by madonuko** [comment]
> we may want to consider making a Ultramarine Desktop identity for installs without a normal edition identity

`ultramarine-release-identity-basic`?

**Comment by nothingneko** [comment]
i think a separate one for desktops may be a good idea, especially since we want to do server

**Comment by lleyton** [comment]
there's already a desktop package, that layers on basic

**Review by lleyton — APPROVED** [review]

**Pull request merged**
