### PR TITLE
feat(comps): include fcitx5 by default in kde

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Comment by lleyton** [comment]
what does upstream (KDE) recommend?

**Comment by madonuko** [comment]
Thought they would recommend fcitx5 but turns out they just tell you both exists

So no, they don't have a preference.

**Comment by lleyton** [comment]
source?

**Comment by madonuko** [comment]
https://userbase.kde.org/Tutorials/Kimpanel

something like this

**Comment by lleyton** [comment]
needs rebase

**Review by lleyton — APPROVED** [review]

**Pull request merged**
