### PR TITLE
Comp updates for 41

### PR DESCRIPTION
**Pull request by nothingneko**
Featuring
- Final removal of Pantheon
- Kustom KDE Komps
- Minor Xfce changes

WIP
- New GNOME tiling extension

### CODE REVIEW

**Comment by madonuko** [comment]
need to separate identity with desktop packages (for Ultramarine Hop)

**Comment by nothingneko** [comment]
we need to figure out what to replace pop shell with soon

**Comment by lleyton** [comment]
Please add the proper obsoletes setup for the new plasma-release and plasma-release-identity package, that way users are migrated on upgrade

https://docs.fedoraproject.org/en-US/packaging-guidelines/#renaming-or-replacing-existing-packages

**Review by lleyton — CHANGES_REQUESTED** [review]
Please add the proper obsoletes setup for the new plasma-release and plasma-release-identity package, that way users are migrated on upgrade

https://docs.fedoraproject.org/en-US/packaging-guidelines/#renaming-or-replacing-existing-packages

**Comment by lleyton** [comment]
additionally, your package does not build

**Comment by nothingneko** [comment]
> Please add the proper obsoletes setup for the new plasma-release and plasma-release-identity package, that way users are migrated on upgrade
> 
> 
> 
> https://docs.fedoraproject.org/en-US/packaging-guidelines/#renaming-or-replacing-existing-packages
> 
> 
> 
> 

got it!

**Review by lleyton — APPROVED** [review]

**Pull request merged**
