### PR TITLE
fix(ci): mass-rebuild

### PR DESCRIPTION
**Pull request by madonuko**

### CODE REVIEW

**Review by nothingneko — DISMISSED** [review]

**Comment by nothingneko** [comment]
Lea and Cappy should look too

**Review by korewaChino — COMMENTED** [review]
explain why push event must be removed

**Comment by madonuko** [comment]
how do you issue mass rebuilds by pushing?

**Comment by korewaChino** [comment]
actually, workflow_dispatch

**Review by korewaChino — APPROVED** [review]

**Pull request merged**
